name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - docs
  pull_request:
    branches:
      - docs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Debug folder structure
        run: |
          ls -lha
          cd ..
          ls -lha
          cd megabouts
          ls -lha
          cd docs
          ls -lha

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install .[doc]

      # - name: Build Sphinx documentation
      #   run: |
      #     cd ../docs
      #     sphinx-build -b html . build/html

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./docs/_build/html
